// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    // get n 
		int n = Integer.parseInt(args[0]);
		int i = 0;
		int below = 0;
		int up = 0;

		while (i < n) {
			double num = Math.random();
			if (num > 0.5) up = up + 1;
			else below = below + 1;
			i = i + 1;
		}
		if (below == 0) 
			System.out.println("error");

		else {
			double ratio;
			if (up<below) ratio = (double) up / below;
			else ratio = (double) below / up;
			System.out.println("> 0.5:  " + up + "times");
			System.out.println("<= 0.5: " + below + "times");
			System.out.println("ratio:  " + ratio);
		}
	}
}
